spring:
  cloud:
     stream:
        default-binder: kafka
        kafka:
           binder:
             zk-nodes: 127.0.0.1:2182,127.0.0.1:2183,127.0.0.1:2184
             brokers: 127.0.0.1:9093,127.0.0.1:9094,127.0.0.1:9095
             autoCreateTopics: true
             autoAddPartitions: true
        bindings:
            person-input:
              destination: person
              group: person
              producer:
                partitionCount: 2
                partitionKeyExpression: payload
            person-output:
              destination: person
              group: person
              producer:
                partitionCount: 2
                partitionKeyExpression: payload

            input:
              destination: test
              group: test
              producer:
                partitionCount: 2
                partitionKeyExpression: payload
            output:
              destination: test
              group: test
              producer:
                partitionCount: 2
                partitionKeyExpression: payload
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
#  kafka:
#    consumer:
#      enable-auto-commit: false

