spring:
  datasource:
    url: jdbc:mysql://wangyaochong:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wangyaochong
    password: qwer@Qwer
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wangyaochong.springsecurityboot.generated.entity

debug: true


server:
  servlet:
    session:
      timeout: 30s
  error:
    whitelabel:
      enabled: false
#      cookie:
#        http-only: true
#        secure: true   #是否使用https传输cookie


