spring:
  redis:
    host: www.wangyaochong.com
    port: 6379
    database: 0
    password: qwer@Qwer
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1


  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
